import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* Bouton TOUJOURS visible */}
          <SidebarTrigger className="fixed top-4 right-4 z-50" />

          {/* Le contenu est déplacé SEULEMENT si variant='inset'. 
              Pour que la sidebar disparaisse complètement, on ne met pas SidebarInset ici */}
          <main className="p-4">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
